"""
tests/test_phase5_integration.py
---------------------------------
CHECK 3 — Phase 0 → Phase 1 → Phase 2 → Phase 3 → Phase 4 → Phase 5 E2E.

Hits the live FastAPI REST endpoints (Phase 5) which read the artifacts
generated by the previous Orchestrator execution.

Part of the Hybrid AI-NWP Multi-Model Forecast Blending System
"""

import sys
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from src.api.main import app

client = TestClient(app)

class TestPhase5Integration:
    def test_health_endpoint(self):
        """Verify the API mounts and can discover enabled models and runs."""
        response = client.get("/health")
        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "ok"
        assert isinstance(data["models_loaded"], list)
        assert len(data["models_loaded"]) > 0
        # The latest run should be populated from the disk cache
        assert data["latest_run"] is not None

    def test_forecast_endpoint(self):
        """Verify the forecast GeoJSON payloads are properly sliced and formed."""
        # Querying t2m at lead hour 24
        response = client.get("/api/v1/forecast/t2m/24")
        assert response.status_code == 200
        data = response.json()
        
        assert data["variable"] == "t2m"
        assert data["lead_hours"] == 24
        assert "features" in data
        assert len(data["features"]) > 0
        
        # Verify GeoJSON structure for the first feature
        feature = data["features"][0]
        assert feature["type"] == "Feature"
        assert "coordinates" in feature["geometry"]
        assert "value" in feature["properties"]
        assert "unit" in feature["properties"]

    def test_weights_endpoint(self):
        """Verify the weight mappings successfully group models by region."""
        response = client.get("/api/v1/weights/t2m?lead_hours=24&season=JJA")
        assert response.status_code == 200
        data = response.json()
        
        assert data["variable"] == "t2m"
        assert "regions" in data
        assert "all_india" in data["regions"]
        
        # Verify WeightEntry structure
        entries = data["regions"]["all_india"]
        assert len(entries) > 0
        assert "model_name" in entries[0]
        assert "weight" in entries[0]
        assert "color" in entries[0]

    def test_skill_endpoint(self):
        """Verify raw skill metrics are returned as flattened rows."""
        response = client.get("/api/v1/skill/scores?variable=t2m&lead_hours=24")
        assert response.status_code == 200
        data = response.json()
        
        assert isinstance(data, list)
        assert len(data) > 0
        assert "rmse" in data[0]
        assert "mae" in data[0]
        assert "ets" in data[0]

    def test_alerts_endpoint(self):
        """Verify extreme alerts endpoint successfully reads the bitmasks."""
        response = client.get("/api/v1/alerts/extreme")
        assert response.status_code == 200
        data = response.json()
        
        assert isinstance(data, list)
        # Even if empty, it must be a list
        if len(data) > 0:
            assert "alert_type" in data[0]
            assert "severity" in data[0]
            assert "lat_center" in data[0]
